export default [
    {
        name: "미디어랩스대학",
        members: [
            { name: "김멋사", vote: "approve", agenda: "1" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "2" },            
            { name: "태완김", vote: "abstain", agenda: "3" },
            { name: "김멋사", vote: "approve", agenda: "4" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "태완김", vote: "abstain", agenda: "3" },
            { name: "김멋사", vote: "approve", agenda: "4" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "5" },
            { name: "태완김", vote: "abstain", agenda: "6" },
            { name: "김멋사", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "5" },
            { name: "태완김", vote: "abstain", agenda: "6" },
            { name: "김멋사", vote: "approve", agenda: "1" },
            { name: "태완김", vote: "abstain", agenda: "3" },
            { name: "김멋사", vote: "approve", agenda: "4" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "5" },
            { name: "태완김", vote: "abstain", agenda: "6" },
            { name: "김멋사", vote: "approve", agenda: "1" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "태완김", vote: "abstain", agenda: "1" },
            { name: "김멋사", vote: "approve", agenda: "1" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "1" },            
            { name: "태완김", vote: "abstain", agenda: "1" },
            { name: "김멋사", vote: "approve", agenda: "1" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "태완김", vote: "abstain", agenda: "1" },
            { name: "김멋사", vote: "approve", agenda: "1" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "태완김", vote: "abstain", agenda: "1" },
            { name: "김멋사", vote: "approve", agenda: "2" },
            { name: "혜진조", vote: "oppose", agenda: "2" },
            { name: "유리이", vote: "abstain", agenda: "2" },
            { name: "태완김", vote: "abstain", agenda: "1" },
        ],
    },
    {
        name: "공과대학",
        members: [
            { name: "태완김", vote: "approve", agenda: "2" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "태완김", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "태완김", vote: "approve", agenda: "3" },
            { name: "유리이", vote: "abstain", agenda: "4" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "태완김", vote: "approve", agenda: "5" },
            { name: "유리이", vote: "abstain", agenda: "6" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "태완김", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "태완김", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "태완김", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "혜진조", vote: "oppose", agenda: "1" },
            { name: "태완김", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "혜진조", vote: "oppose", agenda: "2" },
        ],
    },
    {
        name: "글로벌경영대학",
        members: [
            { name: "혜진조", vote: "approve", agenda: "2" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "태완김", vote: "oppose", agenda: "1" },
            { name: "혜진조", vote: "approve", agenda: "4" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "태완김", vote: "oppose", agenda: "3" },
            { name: "혜진조", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "5" },
            { name: "태완김", vote: "oppose", agenda: "1" },
        ],
    },
    {
        name: "의료과학대학",
        members: [
            { name: "혜진조", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "태완김", vote: "oppose", agenda: "1" },
            { name: "혜진조", vote: "approve", agenda: "2" },
            { name: "유리이", vote: "abstain", agenda: "2" },
            { name: "태완김", vote: "oppose", agenda: "4" },
            { name: "혜진조", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "3" },
            { name: "태완김", vote: "oppose", agenda: "1" },
            { name: "혜진조", vote: "approve", agenda: "5" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "태완김", vote: "oppose", agenda: "1" },
        ],
    },
    {
        name: "인문사회과학대학",
        members: [
            { name: "혜진조", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "2" },
            { name: "태완김", vote: "oppose", agenda: "1" },
            { name: "혜진조", vote: "approve", agenda: "3" },
            { name: "유리이", vote: "abstain", agenda: "2" },
            { name: "태완김", vote: "oppose", agenda: "4" },
            { name: "혜진조", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "태완김", vote: "oppose", agenda: "5" },
            { name: "혜진조", vote: "approve", agenda: "6" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "태완김", vote: "oppose", agenda: "1" },
        ],
    },
    {
        name: "자연과학대학",
        members: [
            { name: "혜진조", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "2" },
            { name: "태완김", vote: "oppose", agenda: "3" },
            { name: "혜진조", vote: "approve", agenda: "4" },
            { name: "유리이", vote: "abstain", agenda: "5" },
            { name: "태완김", vote: "oppose", agenda: "6" },
            { name: "혜진조", vote: "approve", agenda: "2" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "태완김", vote: "oppose", agenda: "1" },
            { name: "혜진조", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "1" },
            { name: "태완김", vote: "oppose", agenda: "1" },
        ],
    },
    {
        name: "SW융합대학",
        members: [
            { name: "혜진조", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "2" },
            { name: "태완김", vote: "oppose", agenda: "1" },
            { name: "혜진조", vote: "approve", agenda: "3" },
            { name: "유리이", vote: "abstain", agenda: "4" },
            { name: "태완김", vote: "oppose", agenda: "1" },
            { name: "혜진조", vote: "approve", agenda: "5" },
            { name: "태완김", vote: "oppose", agenda: "1" },
        ],
    },
    {
        name: "의과대학",
        members: [
            { name: "혜진조", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "2" },
            { name: "태완김", vote: "oppose", agenda: "1" },
            { name: "혜진조", vote: "approve", agenda: "4" },
        ],
    },
    {
        name: "체육대학",
        members: [
            { name: "혜진조", vote: "approve", agenda: "1" },
            { name: "유리이", vote: "abstain", agenda: "2" },
            { name: "태완김", vote: "oppose", agenda: "4" },
            { name: "혜진조", vote: "approve", agenda: "3" },
            { name: "유리이", vote: "abstain", agenda: "5" },
            { name: "혜진조", vote: "approve", agenda: "6" },
            { name: "유리이", vote: "abstain", agenda: "5" },
        ],
    },
]